SELECT A.Nome AS Nome_Assicurazione, A.Sede AS Sede_Assicurazione, COUNT(AUTO.Targa) AS Numero_Auto_Assicurate
FROM ASSICURAZIONI A
LEFT JOIN AUTO ON A.CodAss = AUTO.CodAss
GROUP BY A.Nome, A.Sede;


SELECT A.Targa AS Targa_Auto, COUNT(AUTOCOINVOLTE.CodS) AS Numero_Sinistri
FROM AUTO A
LEFT JOIN AUTOCOINVOLTE ON A.Targa = AUTOCOINVOLTE.Targa
WHERE A.Marca = 'Fiat'
GROUP BY A.Targa;


SELECT AUTO.Targa AS Targa_Auto, ASSICURAZIONI.Nome AS Nome_Assicurazione, SUM(AUTOCOINVOLTE.ImportoDelDanno) AS Totale_Danni
FROM AUTOCOINVOLTE
INNER JOIN AUTO ON AUTOCOINVOLTE.Targa = AUTO.Targa
INNER JOIN ASSICURAZIONI ON AUTO.CodAss = ASSICURAZIONI.CodAss
GROUP BY AUTO.Targa, ASSICURAZIONI.Nome
HAVING COUNT(AUTOCOINVOLTE.CodS) > 1;
