CREATE TABLE Proprietari (
	CodF VARCHAR(16) NOT NULL PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Residenza VARCHAR(128) NULL);

CREATE TABLE Assicurazioni (
	CodAss INT NOT NULL PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Sede VARCHAR(128) NULL);

CREATE TABLE Sinistro (
	CodS INT NOT NULL PRIMARY KEY IDENTITY,
	Localita VARCHAR(50) NOT NULL,
	DataS Date NOT NULL);

CREATE TABLE [Auto] (
	Targa VARCHAR(7) NOT NULL PRIMARY KEY,
	Marca VARCHAR(50) NOT NULL,
	Cilindrata INT NOT NULL,
	Potenza INT NOT NULL,
	CodF VARCHAR(16) NOT NULL,
	CodAss INT NOT NULL,
	CONSTRAINT FK_Auto_Proprietari FOREIGN KEY (CodF) REFERENCES Proprietari(CodF),
	CONSTRAINT FK_Auto_Assicurazioni FOREIGN KEY (CodAss) REFERENCES Assicurazioni(CodAss));

CREATE TABLE AutoCoinvolte (
	CodS INT NOT NULL,
	Targa VARCHAR(7) NOT NULL,
	ImportoDelDanno DECIMAL(8,2),
	PRIMARY KEY  (CodS,Targa),
	CONSTRAINT FK_AutoCoinvolte_Sinistro FOREIGN KEY (Cods) REFERENCES Sinistro(Cods),
	CONSTRAINT FK_AutoCoinvolte_Auto FOREIGN KEY (Targa) REFERENCES [Auto](Targa));